function Global()
{

    /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#ff0105+0,ff0004+60,ff0105+60,ff0004+60,ff0105+60,ff0004+60,ff0004+60,ff0004+60&amp;0+59,1+60,1+60 */
//    background: -moz-linear-gradient(top,  rgba(255,1,5,0) 0%, rgba(255,0,4,0) 59%, rgba(255,0,4,1) 60%); /* FF3.6+ */
//    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,1,5,0)), color-stop(59%,rgba(255,0,4,0)), color-stop(60%,rgba(255,0,4,1))); /* Chrome,Safari4+ */
//    background: -webkit-linear-gradient(top,  rgba(255,1,5,0) 0%,rgba(255,0,4,0) 59%,rgba(255,0,4,1) 60%); /* Chrome10+,Safari5.1+ */
//    background: -o-linear-gradient(top,  rgba(255,1,5,0) 0%,rgba(255,0,4,0) 59%,rgba(255,0,4,1) 60%); /* Opera 11.10+ */
//    background: -ms-linear-gradient(top,  rgba(255,1,5,0) 0%,rgba(255,0,4,0) 59%,rgba(255,0,4,1) 60%); /* IE10+ */
//    background: linear-gradient(to bottom,  rgba(255,1,5,0) 0%,rgba(255,0,4,0) 59%,rgba(255,0,4,1) 60%); /* W3C */
//    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00ff0105', endColorstr='#ff0004',GradientType=0 ); /* IE6-9 */

    this.color =
    {
        white:
        {
            hex:0xffffff,
            rgba:"rgb(255,255,255,1)",
            rgbaHalf:"rgb(255,255,255,0.5)",
            string:"#ffffff"
        },
        black:
        {
            hex:0x000000,
            rgba:"rgb(0,0,0,1)",
            string:"#000000"
        },
        red:
        {
            hex:0xff0000,
            rgba:"rgb(255,0,0,1)",
            string:"#ff0000"
        },
        green:
        {
            hex:0x00ff00,
            rgba:"rgb(0,255,0,1)",
            string:"#00ff00"
        },
        blue:
        {
            hex:0x0000ff,
            rgba:"rgb(0,0,255,1)",
            string:"#0000ff"
        },
        gold:
        {
            hex:0xffd700,
            rgba:"rgb(255,215,0,1)",
            string:"#ffd700"
        },
        grey:
        {
            hex:0xcccccc,
            rgba:"rgb(204,204,204,1)",
            string:"#cccccc"
        },
        gray:
        {
            // Will be the same as grey outside of this block VVVVVVV
            //                                                 VVVVV
            //                                                  VVV
            //                                                   V
        }
    }
    this.color.gray = this.color.grey;
    //background: -webkit-linear-gradient(top,  rgba(255,1,5,0) 0%,rgba(255,0,4,0) 59%,rgba(255,0,4,1) 60%); /* Chrome10+,Safari5.1+ */
    this.orbScale = 0.15;
    this.orbSize = function()
    {
        return (this.width() * this.orbScale);
    };

    this.expBarSize = function()
    {
        return (this.width() - (2 * this.orbSize()));
    };
    var self = this;
    this.domElements =
    {
        list:
        {
            ofLists:
            {
                main:"main",
                inGame:"inGame"
            },
            main:
            [
                "viewport"
                /*
                "navigation",
                "submenu"
                */
            ],
            inGame:
            [
                "healthOrb",
                "manaOrb",
                "expBar",
                "staminaBar",
                "consumablesBar",
                "skillA"
                /*
                "skillButtons",
                "potionBar",
                "hotkeyPanel"
                */
            ],
            chat:
            [
                "bubble",
                "input"
            ]
        },
        main:
        {
            viewport:
            {
                id:"_VIEWPORT_DOM_",
                width:self.width(),
                height:self.height(),
                color:this.color.grey,
                position:null,
                top:null,
                left:null,
                bottom:null,
                right:null
            }
            /*
            navigation:
            {},
            submenu:
            {}
            */
        },
        inGame:
        {
            healthOrb:
            {
                id:"_HEALTH_ORB_DOM_",
                width:self.orbSize(),
                height:self.orbSize(),
                color:this.color.red,
                position:"absolute",
                top:null,
                left:0,
                bottom:0,
                right:null
            },
            manaOrb:
            {
                id:"_MANA_ORB_DOM_",
                width:self.orbSize(),
                height:self.orbSize(),
                color:this.color.blue,
                position:"absolute",
                top:null,
                left:null,
                bottom:0,
                right:0
            },
            expBar:
            {
                id:"_EXP_BAR_DOM_",
                width:self.expBarSize(),
                height:self.orbSize() * .15,
                color:this.color.gold,
                position:"absolute",
                top:null,
                left:self.orbSize(),
                bottom:0,
                right:null
            },
            staminaBar:
            {
                id:"_STAMINA_BAR_DOM_",
                width:self.expBarSize(),
                height:(self.orbSize() * .025) > 0 ? self.orbSize() * .025 : 5,
                color:this.color.white,
                position:"absolute",
                top:null,
                left:self.orbSize(),
                bottom:self.orbSize() * .15,
                right:null
            },
            consumablesBar:
            {
                id:"_CONSUMABLES_BAR_DOM_",
                width:self.expBarSize(),
                height:self.orbSize() * .2,
                color:this.color.grey,
                position:"absolute",
                top:null,
                left:self.orbSize(),
                bottom:self.orbSize() * .175,
                right:null
            },
            skillA:
            {
                id:"_SKILL_A_DOM_",
                width:self.orbSize() * .4,
                height:self.orbSize() * .4,
                color:this.color.green,
                position:"absolute",
                top:null,
                left:self.orbSize(),
                bottom:self.orbSize() * .375,
                right:null
            },
            skillB:
            {
                id:"_SKILL_B_DOM_",
                width:self.orbSize() * .4,
                height:self.orbSize() * .4,
                color:this.color.green,
                position:"absolute",
                top:null,
                left:null,
                bottom:self.orbSize() * .375,
                right:self.orbSize()
            },
            hotkeyBar:
            {
                id:"_HOTKEY_BAR_DOM_",
                width:self.expBarSize() - (2 * (self.orbSize() * .4)),
                height:(self.orbSize() * .4) * .66,
                color:this.color.red,
                position:"absolute",
                top:null,
                left:self.orbSize() + (self.orbSize() * .4),
                bottom:self.orbSize() * .375,
                right:null
            }
            /*
            skillButtons:
            {},
            potionBar:
            {},
            hotkeyPanel:
            {}

            //  Template for these styles (plz update all dem niggs if chaeng thx)
                id:null,
                width:null,
                height:null,
                color:null,
                position:null,
                top:null,
                left:null,
                bottom:null,
                right:null
            //

            */
        },
        chat:
        {
            bubble:
            {
                id:"_BUBBLE_DOM_",
                width:self.bubbleSize(),
                color:this.color.grey,
                position:"absolute",
                top:0,
                left:0
            },
            input:
            {
                id:"_CHAT_INPUT_DOM_",
                width:self.chatInputSize(),
                height:25,
                color:this.color.grey,
                position:"absolute",
                bottom:this.orbSize(),
                left:0
            }
        }
    }

    this.entities =
    {
        types:
        [
            "inanimate",
            "interactable",
            "items",
            "mobs",
            "npc",
            "hero"
        ],
        inanimate:
        [

        ],
        interactable:
        [

        ],
        items:
        {
            armour:
            {
                belts:
                [
                    sash:"",
                    light_belt:"",
                    belt:"",
                    heavy_belt:"",
                    plated_belt:"",
                    demonhide_sash:"",
                    sharkskin_belt:"",
                    mesh_belt:"",
                    battle_belt:"",
                    war_belt:"",
                    spiderweb_sash:"",
                    vampirefang_belt:"",
                    mithril_coil:"",
                    troll_belt:"",
                    colossus_girdle:""
                ],
                bodyArmour:
                [
                    quilted_armour:"",
                    leather_armour:"",
                    hard_leather_armour:"",
                    studded_leather:"",
                    ring_mail:"",
                    scale_mail:"",
                    chain_mail:"",
                    breast_plate:"",
                    splint_mail:"",
                    plate_mail:"",
                    field_plate:"",
                    gothic_plate:"",
                    light_plate:"",
                    full_plate_mail:"",
                    ancient_armour:"",
                    ghost_armour:"",
                    serpentskin_armour:"",
                    demonhide_armour:"",
                    trellised_armour:"",
                    linked_mail:"",
                    tigulated_mail:"",
                    mesh_armour:"",
                    cuirass:"",
                    russet_armour:"",
                    templar_coat:"",
                    sharktooth_armour:"",
                    embossed_plate:"",
                    mage_plate:"",
                    chaos_armour:"",
                    ornate_plate:"",
                    dusk_shroud:"",
                    wyrmhide:"",
                    scarab_husk:"",
                    wire_fleece:"",
                    diamond_mail:"",
                    loricated_mail:"",
                    boneweave:"",
                    great_hauberk:"",
                    balrog_skin:"",
                    hellforged_plate:"",
                    kraken_shell:"",
                    lacquered_plate:"",
                    archon_plate:"",
                    shadow_plate:"",
                    sacred_armour:""
                ],
                boots:
                [
                    boots:"",
                    heavy_boots:"",
                    chain_boots:"",
                    light_plated_boots:"",
                    greaves:"",
                    demonhide_boots:"",
                    sharkskin_boots:"",
                    mesh_boots:"",
                    battle_boots:"",
                    war_boots:"",
                    wyrmhide_boots:"",
                    scarabshell_boots:"",
                    boneweave_boots:"",
                    mirrored_boots:"",
                    myrmidon_greaves:""
                ],
                gloves:
                [
                    leather_gloves:"",
                    heavy_gloves:"",
                    chain_gloves:"",
                    light_gauntlets:"",
                    gauntlets:"",
                    demonhide_gloves:"",
                    sharkskin_gloves:"",
                    heavy_bracers:"",
                    battle_gauntlets:"",
                    war_gauntlets:"",
                    bramble_mitts:"",
                    vampirebone_gloves:"",
                    vambraces:"",
                    crusader_gauntlets:"",
                    ogre_gauntlets:""
                ],
                helms:
                [
                    cap:"",
                    skull_cap:"",
                    helm:"",
                    full_helm:"",
                    mask:"",
                    bone_helm:"",
                    great_helm:"",
                    crown:"",
                    war_hat:"",
                    sallet:"",
                    casque:"",
                    basinet:"",
                    death_mask:"",
                    grim_helm:"",
                    winged_helm:"",
                    grand_crown:"",
                    shako:"",
                    hydraskull:"",
                    armet:"",
                    giant_conch:"",
                    demonhead:"",
                    bone_visage:"",
                    spired_helm:"",
                    corona:""
                ]
            },
            consumables:
            {
                scrolls:
                [
                    scroll_of_identify:"",
                    scroll_of_town_portal:""
                ],
                tomes:
                [
                    tome_of_identify:"",
                    tome_of_town_portal:""
                ],
                potions:
                {
                    healing:
                    [
                        minor_healing:"",
                        light_healing:"",
                        healing:"",
                        greater_healing:"",
                        super_healing:"",
                        grand_healing:"",
                        ultra_healing:""
                    ],
                    mana:
                    [
                        minor_mana:"",
                        light_mana:"",
                        mana:"",
                        greater_mana:"",
                        super_mana:"",
                        grand_mana:"",
                        ultra_mana:""
                    ],
                    rejuvination:
                    [
                        quarter_rejuvination:"",
                        third_rejuvination:"",
                        half_rejuvination:"",
                        two-thirds_rejuvination:"",
                        three-quarters_rejuvination:"",
                        full_rejuvination:""
                    ]
                },
                keys:
                [
                    normal_key:""
                ],
                other:
                [
                    antidote_potion:"",
                    thawing_potion:"",
                    stamina_potion:"",
                    book_of_skill:"",
                    book_of_stats:"",
                    potion_of_life:"",
                    scroll_of_resistance:""
                ]
            },
            jewelleries:
            {
                amulet:"",
                ring:""
            },
            passives:
            {
                charms:
                [
                    small_charm:"",
                    medium_charm:"",
                    large_charm:"",
                    grand_charm:""
                ]
            },
            questItems:
            {

            },
            shields:
            [
                buckler:"",
                small_shield:"",
                large_shield:"",
                kite_shield:"",
                spiked_shield:"",
                bone_shield:"",
                tower_shield:"",
                gothic_shield:"",
                defender:"",
                round_shield:"",
                scutum:"",
                dragon_shield:"",
                barbed_shield:"",
                grim_shield:"",
                pavise:"",
                ancient_shield:"",
                heater:"",
                luna:"",
                hyperion:"",
                monarch:"",
                blade_warrior:"",
                troll_nest:"",
                aegis:"",
                ward:""
            ],
            socketables:
            {
                gems:
                [
                    ruby:"",
                    sapphire:"",
                    topaz:"",
                    emerald:"",
                    diamond:"",
                    amethyst:"",
                    onyx:""
                ],
                jewel:"",
                runes:
                [
                    el:"",
                    eld:"",
                    tir:"",
                    nef:"",
                    eth:"",
                    ith:"",
                    tal:"",
                    ral:"",
                    ort:"",
                    thul:"",
                    amn:"",
                    sol:"",
                    shael:"",
                    dol:"",
                    hel:"",
                    io:"",
                    lum:"",
                    ko:"",
                    fal:"",
                    lem:"",
                    pul:"",
                    um:"",
                    mal:"",
                    ist:"",
                    gul:"",
                    vex:"",
                    ohm:"",
                    lo:"",
                    sur:"",
                    ber:"",
                    jah:"",
                    cham:"",
                    zod:""
                ]
            },
            specials:
            {
                horadric_cube:""
            },
            weapons:
            {
                axes:
                {
                    oneHanded:
                    [
                        hand_axe:"",
                        axe:"",
                        double_axe:"",
                        military_pick:"",
                        war_axe:"",
                        hatchet:"",
                        cleaver:"",
                        twin_axe:"",
                        crowbill:"",
                        naga:"",
                        tomahawk:"",
                        small_crescent:"",
                        ettin_axe:"",
                        war_spike:"",
                        berserker_axe:""
                    ],
                    twoHanded:
                    [
                        large_axe:"",
                        broad_axe:"",
                        battle_axe:"",
                        great_axe:"",
                        giant_axe:"",
                        military_axe:"",
                        bearded_axe:"",
                        tabar:"",
                        gothic_axe:"",
                        ancient_axe:"",
                        feral_axe:"",
                        silver-edged_axe:"",
                        decapitator:"",
                        champion_axe:"",
                        glorious_axe:""
                    ]
                },
                bows:
                [
                    short_bow:"",
                    hunting_bow:"",
                    long_bow:"",
                    composite_bow:"",
                    short_battle_bow:"",
                    long_battle_bow:"",
                    short_war_bow:"",
                    long_war_bow:"",
                    edge_bow:"",
                    razor_bow:"",
                    cedar_bow:"",
                    double_bow:"",
                    short_siege_bow:"",
                    large_siege_bow:"",
                    rune_bow:"",
                    gothic_bow:"",
                    spider_bow:"",
                    blade_bow:"",
                    shadow_bow:"",
                    great_bow:"",
                    diamond_bow:"",
                    crusader_bow:"",
                    ward_bow:"",
                    hydra_bow:""
                ],
                crossbows:
                [
                    light_crossbow:"",
                    crossbow:"",
                    heavy_crossbow:"",
                    repeating_crossbow:"",
                    arbalest:"",
                    siege_crossbow:"",
                    ballista:"",
                    chu-ko-nu:"",
                    pellet_bow:"",
                    gorgon_crossbow:"",
                    colossus_crossbow:"",
                    demon_crossbow:""
                ],
                daggers:
                [
                    dagger:"",
                    dirk:"",
                    kris:"",
                    blade:"",
                    poignard:"",
                    rondel:"",
                    cinquedeas:"",
                    stiletto:"",
                    bone_knife:"",
                    mithril_point:"",
                    fanged_knife:"",
                    legend_spike:""
                ],
                fists:
                [

                ],
                javelins:
                [
                    javelin:"",
                    pilum:"",
                    short_spear:"",
                    glaive:"",
                    throwing_spear:"",
                    war_javelin:"",
                    great_pilum:"",
                    simbilan:"",
                    spiculum:"",
                    harpoon:"",
                    hyperion_javelin:"",
                    stygian_pilum:"",
                    balrog_spear:"",
                    ghost_glaive:"",
                    winged_harpoon:""
                ],
                maces:
                [
                    club:"",
                    spiked_club:"",
                    mace:"",
                    morning_star:"",
                    flail:"",
                    war_hammer:"",
                    maul:"",
                    great_maul:"",
                    cudgel:"",
                    barbed_club:"",
                    flanged_mace:"",
                    jagged_star:"",
                    knout:"",
                    battle_hammer:"",
                    war_club:"",
                    martel_de_fer:"",
                    truncheon:"",
                    tyrant_club:"",
                    reinforced_mace:"",
                    devil_star:"",
                    scourge:"",
                    legendary_mallet:"",
                    ogre_maul:"",
                    thunder_maul:""
                ],
                polearms:
                [
                    bardiche:"",
                    voulge:"",
                    scythe:"",
                    poleaxe:"",
                    halberd:"",
                    war_scythe:"",
                    lochbar_axe:"",
                    bill:"",
                    battle_scythe:"",
                    partizan:"",
                    bee-de-corbian:"",
                    grim_scythe:"",
                    ogre_axe:"",
                    colossus_voulge:"",
                    thresher:"",
                    cryptic_axe:"",
                    great_poleaxe:"",
                    giant_thresher:""
                ],
                scepters:
                [
                    scepter:"",
                    grand_scepter:"",
                    war_scpeter:"",
                    rune_scepter:"",
                    holy_water_sprinkler:"",
                    divine_scepter:"",
                    mighty_scepter:"",
                    seraph_rod:"",
                    caduceus:""
                ],
                spears:
                [
                    spear:"",
                    trident:"",
                    brandistock:"",
                    spetum:"",
                    pike:"",
                    war_spear:"",
                    fuscina:"",
                    war_fork:"",
                    yari:"",
                    lance:"",
                    hyperion_spear:"",
                    stygian_pike:"",
                    mancatcher:"",
                    ghost_spear:"",
                    war_pike:""
                ],
                staves:
                [
                    short_staff:"",
                    long_staff:"",
                    gnarled_staff:"",
                    battle_staff:"",
                    war_staff:"",
                    jo_staff:"",
                    quarterstaff:"",
                    cedar_staff:"",
                    gothic_staff:"",
                    rune_staff:"",
                    walking_stick:"",
                    stalagmite:"",
                    elder_staff:"",
                    shillelagh:"",
                    archon_staff:""
                ],
                swords:
                {
                    oneHanded:
                    [
                        short_sword:"",
                        scimitar:"",
                        sabre:"",
                        falchion:"",
                        crystal_sword:"",
                        broad_sword:"",
                        long_sword:"",
                        war_sword:"",
                        galdius:"",
                        cutlass:"",
                        shamshir:"",
                        tulwar:"",
                        dimensional_blade:"",
                        battle_sword:"",
                        rune_sword:"",
                        ancient_sword:"",
                        falcata:"",
                        ataghan:"",
                        elegant_blade:"",
                        hydra_edge:"",
                        phase_blade:"",
                        conquest_sword:"",
                        cryptic_sword:"",
                        mythical_sword:""
                    ],
                    twoHanded:
                    [
                        two-handed_sword:"",
                        claymore:"",
                        giant_sword:"",
                        bastard_sword:"",
                        flamberge:"",
                        great_sword:"",
                        espandon:"",
                        dacian_falx:"",
                        tusk_sword:"",
                        gothic_sword:"",
                        zweihander:"",
                        executioner_sword:"",
                        legend_sword:"",
                        highland_blade:"",
                        balrog_blade:"",
                        champion_sword:"",
                        colossus_sword:"",
                        colossus_blade:""
                    ]
                }
            }
        },
        mobs:
        {
            undead:
            [
                "zombie",
                "skeleton",
                "skeleton_archer",
                "vampire",
                "wraith"
            ],
            demon:
            [
                "blood_hawk",
                "fallen",
                "fallen_shaman",
                "giant_spider",
                "goatman",
                "spike_fiend",
                "wendigo",
                "hell_bovine"
            ],
            animal:
            [

            ],
            boss:
            [

            ]
        },
        npc:
        [

        ],
        hero:"hero"

    }

    this.zVal =
    {
        camera:
        {
            dev:1000
        }
    }

    this.delimeter = "_";
}

Global.prototype.width = function()
{
    return parseInt(window.innerWidth, 10);
};
Global.prototype.height = function()
{
    return parseInt(window.innerHeight, 10);
};

// Initialize
Global.prototype.init = function()
{
    this.viewport.init();
} // End init

// Return viewport object
Global.prototype.getViewport = function()
{
    return this.viewport;
} // End getViewport

// Return players health
Global.prototype.getPlayerhealth = function()
{
    return this.viewport;
} // End getViewport

Global.prototype.setRenderer = function(renderer)
{
    this.viewport.appendRenderer(renderer.domElement)
}

Global.prototype.resize = function(event)
{
    this.viewport.resize(event);
}

Global.prototype.setBubbleManager = function(bMan)
{
    this.bubbleManager = bMan;
}

Global.prototype.getNewBubbleId = function()
{
    return this.bubbleManager.getNewBubbleId();
}
